//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONGC_hospitality
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormStatus
    {
        public int SerialNo { get; set; }
        public int FormId { get; set; }
        public Nullable<int> ByEmpID { get; set; }
        public Nullable<int> ToEmpID { get; set; }
        public string Status { get; set; }
        public string EventDate { get; set; }
    }
}
