//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONGC_hospitality
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormDetail
    {
        public int FormId { get; set; }
        public string EventN { get; set; }
        public string Department { get; set; }
        public string Venue { get; set; }
        public string EventDate { get; set; }
        public Nullable<int> LightRefreshment { get; set; }
        public Nullable<int> HighTea { get; set; }
        public Nullable<int> LunchWLv { get; set; }
        public Nullable<int> LunchWLnv { get; set; }
        public Nullable<int> LunchSv { get; set; }
        public Nullable<int> LunchSnv { get; set; }
        public Nullable<int> LunchVIPv { get; set; }
        public Nullable<int> LunchVIPnv { get; set; }
        public Nullable<int> LunchVVIPv { get; set; }
        public Nullable<int> LunchVVIPnv { get; set; }
        public Nullable<int> DinnerSv { get; set; }
        public Nullable<int> DinnerSnv { get; set; }
        public Nullable<int> DinnerVIPv { get; set; }
        public Nullable<int> DinnerVIPnv { get; set; }
        public Nullable<int> DinnerVVIPv { get; set; }
        public Nullable<int> DinnerVVIPnv { get; set; }
        public Nullable<int> MinWater { get; set; }
        public Nullable<int> ByEmpID { get; set; }
        public Nullable<int> ToEmpID { get; set; }
    }
}
