//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONGC_hospitality
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ONGCEntityFramework : DbContext
    {
        public ONGCEntityFramework()
            : base("name=ONGCEntityFramework")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FormDetail> FormDetails { get; set; }
        public virtual DbSet<FormStatus> FormStatus1 { get; set; }
        public virtual DbSet<LoginTable> LoginTables { get; set; }
    }
}
